platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'Example' do
    pod 'SnapKit'
    pod 'Kingfisher'
    pod 'DTCoreText'
    pod 'Nantes'
    pod 'Moya/RxSwift'
    pod 'RxCocoa'
end
